apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.app.name }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
data:
  CONFIG_ENV: "{{ .Values.config.env }}"